name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install RipGrep
        run: sudo apt-get install ripgrep
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Ensure there are no duplicate dependencies
        run: yarn dedupe
      - name: Build it
        run: yarn build
      - name: Lint it
        run: yarn lint
      - name: Test it
        run: yarn test
